import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/modules/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full overflow-hidden bg-emerald-600/90 select-none">
      <body
        className={`${inter.className}`}
      >
        <SessionWrapper>
          <div>{children}</div>
        </SessionWrapper>
      </body>
    </html>
  );
}
