import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/modules/SessionWrapper";
import Header from "@/components/modules/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="-z-10 h-full w-full overflow-hidden">
      <body
        className={`${inter.className} absolute top-0 h-screen w-screen z-[-2] bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]`}
      >
        <SessionWrapper>
          <Header />
          <div>{children}</div>
        </SessionWrapper>
      </body>
    </html>
  );
}
